[package]
name = "rustburn"
version = "0.1.0"
authors = ["Paul Dejean <paulcdejean@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
path = "rust/lib.rs"

[build]
target = "wasm32-wasi"

[profile.dev]
opt-level = "s"
strip = "debuginfo"
